AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create Codecommit repository, CodePipeline
Parameters:
  CodeCommitName:
    Type: String
    Default: AutomatoonzRepo

Resources:
  CodecommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref CodeCommitName
      RepositoryDescription: Repo created for automatoonz team infra Code
      Tags:
        - Key: Team
          Value: Automatoonz